name: build our image

on:
  push:
    branches:
      - main
  workflow_dispatch: ~

jobs:
  build-7:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: "docker buildx build --pull --push --tag rdey/redis-ssl-dev:7 --platform linux/amd64,linux/arm64 ."
